name: nitro_intelligence

on:
  push:

jobs:
  ruby:
    uses: powerhome/github-actions-workflows/.github/workflows/ruby-gem.yml@7cf2f074c8247f1a3a07e0c759ef7008678de3f3 # main
    with:
      package: ${{ github.workflow }}
      workdir: .
      ruby: '["3.3"]'
    secrets: inherit
