name: nitro_intelligence

on:
  push:

jobs:
  ruby:
    uses: powerhome/github-actions-workflows/.github/workflows/ruby-gem.yml@e1dc1a124d15641fd043616d59465cb6d2c90187 # main
    with:
      package: ${{ github.workflow }}
      workdir: .
      ruby: '["3.3"]'
      before_build: |
        sudo apt-get update
        sudo apt-get install --no-install-recommends -y imagemagick
    secrets: inherit
