name: nitro_intelligence

on:
  push:

jobs:
  ruby:
    uses: powerhome/github-actions-workflows/.github/workflows/ruby-gem.yml@b653a7e39d951c5bea3abf5729575ef41911987c # main
    with:
      package: ${{ github.workflow }}
      workdir: .
      ruby: '["3.3"]'
    secrets: inherit
